// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_posts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPosts = `-- name: CreatePosts :one
INSERT INTO posts (id, title, url, description, feed_id, created_at, updated_at, published_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, url, title, created_at, updated_at, description, published_at, feed_id
`

type CreatePostsParams struct {
	ID          uuid.UUID
	Title       string
	Url         string
	Description string
	FeedID      uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	PublishedAt time.Time
}

func (q *Queries) CreatePosts(ctx context.Context, arg CreatePostsParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPosts,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.FeedID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}
