// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_next_feed.sql

package database

import (
	"context"
)

const getNextFeed = `-- name: GetNextFeed :one

SELECT id, created_at, updated_at, url, name, user_id, last_fetched_at FROM feeds
    ORDER BY last_fetched_at DESC 
    NULLS FIRST
    LIMIT 1
`

func (q *Queries) GetNextFeed(ctx context.Context) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getNextFeed)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.Name,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}
