// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset_db.sql

package database

import (
	"context"
)

const resetDb = `-- name: ResetDb :exec
TRUNCATE TABLE users
`

func (q *Queries) ResetDb(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetDb)
	return err
}
